version: '3'
services:
  rabbitmq:
    image: docker.io/library/rabbitmq:3.11.0-management-alpine
    volumes:
      - ./rabbitData/data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hello-dapr
    hostname: "rabbitmq"
    container_name: "rabbitmq"  
  publisher:
    image: localhost/publishernodapr:1.0.0
    ports:
      - "6003:6003"
    depends_on:
      - rabbitmq
    networks:
      - hello-dapr  
  subscriber1:
    image: localhost/subscribernodapr:1.0.0
    ports:
      - "6002:6002"      
    depends_on:
      - rabbitmq
    networks:
    - hello-dapr  
  subscriber2:
    image: localhost/subscribernodapr:1.0.0
    ports:
      - "5002:6002"      
    depends_on:
      - rabbitmq
    networks:
      - hello-dapr    
networks:
  hello-dapr: